language: go

go:
- 1.5
- 1.6
- 1.7
- 1.8
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

script:
- make build
- make test
- ./converter --list-filters
- make cover
- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
